// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3nNVykdPt6kLtPsk4c5dj81Luat7reI',
    appId: '1:1081726199722:web:f20763510eb9181fd0add3',
    messagingSenderId: '1081726199722',
    projectId: 'new-hms-3291d',
    authDomain: 'new-hms-3291d.firebaseapp.com',
    storageBucket: 'new-hms-3291d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvC4FFNAlhN0mUMp3knqv7KKwiK6ulCDM',
    appId: '1:1081726199722:android:93f1596277f86ec8d0add3',
    messagingSenderId: '1081726199722',
    projectId: 'new-hms-3291d',
    storageBucket: 'new-hms-3291d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGYx4iC6_s2PG3mAPXxTkUbdX1X8c-0I',
    appId: '1:1081726199722:ios:b45d4af326a09937d0add3',
    messagingSenderId: '1081726199722',
    projectId: 'new-hms-3291d',
    storageBucket: 'new-hms-3291d.firebasestorage.app',
    iosBundleId: 'com.example.newhms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGYx4iC6_s2PG3mAPXxTkUbdX1X8c-0I',
    appId: '1:1081726199722:ios:b45d4af326a09937d0add3',
    messagingSenderId: '1081726199722',
    projectId: 'new-hms-3291d',
    storageBucket: 'new-hms-3291d.firebasestorage.app',
    iosBundleId: 'com.example.newhms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ3nNVykdPt6kLtPsk4c5dj81Luat7reI',
    appId: '1:1081726199722:web:23b19f41cad6dc92d0add3',
    messagingSenderId: '1081726199722',
    projectId: 'new-hms-3291d',
    authDomain: 'new-hms-3291d.firebaseapp.com',
    storageBucket: 'new-hms-3291d.firebasestorage.app',
  );

}